[package]
name = "pulldown-cmark-toc"
version = "0.1.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pulldown-cmark = "0.7.2"
regex = "1.3.9"
